// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Testimonial {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    username: string;
    avatar: { data: Media };
    postedAt: Date;
    content: string;
  };
}
export interface Testimonial_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  username: string;
  avatar: Media;
  postedAt: Date;
  content: string;
}

export interface Testimonial_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  username: string;
  avatar: number;
  postedAt: Date;
  content: string;
}

export interface Testimonial_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  username: string;
  avatar: AdminPanelRelationPropertyModification<Media>;
  postedAt: Date;
  content: string;
}
